[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"

[[services]]
name = "backend"
source = "."
[services.build]
buildCommand = "cd backend && npm install"
startCommand = "cd backend && npm start" 