[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"

[build.buildCommand]
build = "npm install"

[build.startCommand]
start = "npm start" 